In [41]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [33]:
# Importing the dataset and Extracting the Independent and Dependent variables
data= pd.read_csv('New_GDP.csv')
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values

In [42]:
data.head()
y

array([ 286147,  294267,  312177,  325431,  333766,  352766,  348500,
        374948,  383153,  410279,  423011,  431960,  453829,  488247,
        470402,  475190,  513860,  527270,  561630,  589787,  595741,
        593843,  620872,  628079,  684634,  693191,  744972,  785965,
        745083,  798506,  843426,  868092,  936270,  973357, 1013866,
       1057612, 1094993, 1206243, 1280228, 1347889, 1367171, 1440504,
       1522344, 1619694, 1737741, 1876319, 1957032, 2087828, 2246276,
       2342774, 2472052, 2570690, 2777813, 2971464, 3253073, 3564364,
       3896636, 4158676, 4516071, 4937006, 5243582])

In [43]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [44]:
# Fitting Multiple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [45]:
# Predicting the Test set results
y_pred = model.predict(X_test)
y_pred

array([ 744398.49018291, 1057768.82451854, 5246878.15999319,
        743708.0811659 ,  431386.63250571,  311374.33817307,
       1014284.97422693, 4938565.71577375, 1366771.1815247 ,
        619753.26256958,  333641.46656212,  422301.92909074,
        844358.86946984])

In [46]:
# Calculating the Coefficients
print(model.coef_)

[ 8.67662895e-01  1.81285543e-01  9.89351303e-01 -4.76427868e-01
  4.85305278e-02  9.99469859e-01  1.51317204e+02]


In [ ]:
# Calculating the Intercept
print(model.intercept_)

10926.382732179249


In [48]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9999994188450557

In [32]:
# Calculating the R squared value


import pickle
filename = 'new_model1.sav'
pickle.dump(model, open(filename, 'wb'))
load_model = pickle.load(open(filename,'rb'))
load_model.predict([[739495,630540,1442498,108249,823023,3061589,2011]])

array([5546637.54046881])