In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score,roc_auc_score,roc_curve

In [2]:
df=pd.read_csv('JSS_N.csv')
df.shape

(139, 18)

In [3]:
df.head()

Age (in years)  Gender(0=F,1=M)  DOE NYHA Class  PND(1=present,0-absent)  \
0              70                0               1                        1   
1              38                1               0                        1   
2              31                1               0                        0   
3              72                1               1                        0   
4              65                1               1                        0   

   Orthopnoea  AOE NYHA Class  Palpitations  Easy Fatiguability  Pre-Syncope  \
0           0               0             0                   1            0   
1           0               0             0                   0            0   
2           0               0             0                   0            0   
3           0               1             0                   0            0   
4           0               2             0                   1            1   

   Syncope  PVD / PAD  IHD  DCM  DM  HTN  SCD  RWMA(seen=1, not seen=0)  COPD  
0        0          0    0    0   0    0    0                         1     0  
1        0          0    0    0   1    1    0                         1     0  
2        0          0    0    0   1    0    0                         1     0  
3        0          0    0    0   0    0    0                         0     0  
4        0          0    0    0   0    0    0                         1     0

In [ ]:
# cont=0
# p=[0,1,2,3]
# for i in range(len(df)):
#   for j in range(len(df[0])):
#     if (df[i,j]!=0):
#       cont+=1
# cont

In [ ]:
# df.target.value_counts()


In [5]:
target_name="COPD"
y=df[target_name]
x=df[["Age (in years)","DOE NYHA Class",	"RWMA(seen=1, not seen=0)","Syncope",	"Orthopnoea","Pre-Syncope"]]

In [6]:
x.columns

Index(['Age (in years)', 'DOE NYHA Class', 'RWMA(seen=1, not seen=0)',
       'Syncope', 'Orthopnoea', 'Pre-Syncope'],
      dtype='object')

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42, shuffle =True)

#Models without Optimal Features

1.1) RFC

In [9]:
from sklearn.ensemble import RandomForestClassifier

RFC= RandomForestClassifier()
rf1=RandomForestClassifier(max_samples=0.75,random_state=42)
import datetime
start=datetime.datetime.now()
RFC.fit(x_train,y_train)
rf1.fit(x_train,y_train)
end=datetime.datetime.now()
print("Total time of exection :",end-start)

y_pred1=rf1.predict(x_test)
rfc_pred_proba=rf1.predict_proba(x_test)[:,1]
y_pred=RFC.predict(x_test)
rfc_pred_proba=RFC.predict_proba(x_test)[:,1]

print("Accuracy Score",accuracy_score(y_test,y_pred1)*100)
print("Accuracy Score",accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classificaiton Report:\n",classification_report(y_test,y_pred,digits=4))
# print("ROC AUC Score",roc_auc_score(y_test,rfc_pred_proba))


Total time of exection : 0:00:00.283177
Accuracy Score 92.85714285714286
Accuracy Score 92.85714285714286
Confusion Matrix:
 [[26  1]
 [ 1  0]]
Classificaiton Report:
               precision    recall  f1-score   support

           0     0.9630    0.9630    0.9630        27
           1     0.0000    0.0000    0.0000         1

    accuracy                         0.9286        28
   macro avg     0.4815    0.4815    0.4815        28
weighted avg     0.9286    0.9286    0.9286        28



1.2) KNN Classifier

In [24]:
from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

print("Accuracy Score",accuracy_score(y_test,y_pred)*100)
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classificaiton Report:\n",classification_report(y_test,y_pred,digits=4))

import pickle
filename = 'JSS_model.sav'
pickle.dump(model, open(filename, 'wb'))
load_model = pickle.load(open(filename,'rb'))
load_model.predict([[ 38,0,1,0,0,0]])


Accuracy Score 96.42857142857143
Confusion Matrix:
 [[27  0]
 [ 1  0]]
Classificaiton Report:
               precision    recall  f1-score   support

           0     0.9643    1.0000    0.9818        27
           1     0.0000    0.0000    0.0000         1

    accuracy                         0.9643        28
   macro avg     0.4821    0.5000    0.4909        28
weighted avg     0.9298    0.9643    0.9468        28



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/u

array([0])

1.3) Suport Vector Classifier (SVC)

In [13]:
from sklearn.svm import SVC

model=SVC(probability=True)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)

print("SVC-Model : Test Accuracy ",round(accuracy_score(y_test,y_pred)*100,2))
print("Classificaiton Report:\n",classification_report(y_test,y_pred,digits=4))
print("SVC-Model : Confusion Matrix:\n",confusion_matrix(y_test,y_pred))


SVC-Model : Test Accuracy  96.43
Classificaiton Report:
               precision    recall  f1-score   support

           0     0.9643    1.0000    0.9818        27
           1     0.0000    0.0000    0.0000         1

    accuracy                         0.9643        28
   macro avg     0.4821    0.5000    0.4909        28
weighted avg     0.9298    0.9643    0.9468        28

SVC-Model : Confusion Matrix:
 [[27  0]
 [ 1  0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


1.4) Linear Discriminant Analysis (LDA)

In [14]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA()
lda.fit(x_train,y_train)

y_pred=lda.predict(x_test)

print("Accuracy Score",round(accuracy_score(y_test,y_pred)*100,2))
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Classificaiton Report:\n",classification_report(y_test,y_pred,digits=4))

Accuracy Score 92.86
Confusion Matrix:
 [[26  1]
 [ 1  0]]
Classificaiton Report:
               precision    recall  f1-score   support

           0     0.9630    0.9630    0.9630        27
           1     0.0000    0.0000    0.0000         1

    accuracy                         0.9286        28
   macro avg     0.4815    0.4815    0.4815        28
weighted avg     0.9286    0.9286    0.9286        28



Now applying Boruta Method

In [15]:
!pip install Boruta

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.9/57.9 kB 2.5 MB/s eta 0:00:00


In [17]:
from boruta import BorutaPy

feat_selector=BorutaPy(RFC,n_estimators='auto',verbose=2,random_state=1)
# feat_selector.fit(x,y)

In [18]:
 feat_selector.fit(x,y)

Iteration: 	1 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	2 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	3 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	4 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	5 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	6 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	7 / 100
Confirmed: 	0
Tentative: 	6
Rejected: 	0
Iteration: 	8 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	9 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	10 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	11 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	12 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	13 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	14 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	15 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	16 / 100
Confirmed: 	0
Tentative: 	1
Rejected: 	5
Iteration: 	17 / 

BorutaPy(estimator=RandomForestClassifier(n_estimators=14,
                                          random_state=RandomState(MT19937) at 0x7C7D96335D40),
         n_estimators='auto',
         random_state=RandomState(MT19937) at 0x7C7D96335D40, verbose=2)

2.)Identify most important feature using Boruta Feature Selection


In [19]:
feat_selector.support_

array([False, False, False, False, False, False])

In [20]:
print("Ranking",feat_selector.ranking_)

Ranking [2 3 4 6 6 6]


In [ ]:
print("No. of significant features:", feat_selector.n_features_)

No. of significant features: 0


In [ ]:
selected_rf_features=pd.DataFrame({"feature":list(x_train.columns),'Ranking':feat_selector.ranking_})
selected_rf_features.sort_values(by='Ranking')

feature  Ranking
0             Age (in years)        2
2             DOE NYHA Class        3
16  RWMA(seen=1, not seen=0)        4
9                    Syncope        5
4                 Orthopnoea        6
8                Pre-Syncope        7
7         Easy Fatiguability        8
5             AOE NYHA Class        9
1            Gender(0=F,1=M)        9
6               Palpitations       11
10                 PVD / PAD       12
14                       HTN       13
13                        DM       14
3    PND(1=present,0-absent)       15
11                       IHD       16
15                       SCD       17
12                       DCM       17

3.)Create Optimal Features

In [ ]:
# x=x.to_numpy()
# y=y.to_numpy()
best_features=feat_selector.transform(x)

In [ ]:
best_features.shape

(139, 0)

In [ ]:
best_features

array([], shape=(139, 0), dtype=int64)

In [ ]:
df.head()

Age (in years)  Gender(0=F,1=M)  DOE NYHA Class  PND(1=present,0-absent)  \
0              70                0               1                        1   
1              38                1               0                        1   
2              31                1               0                        0   
3              72                1               1                        0   
4              65                1               1                        0   

   Orthopnoea  AOE NYHA Class  Palpitations  Easy Fatiguability  Pre-Syncope  \
0           0               0             0                   1            0   
1           0               0             0                   0            0   
2           0               0             0                   0            0   
3           0               1             0                   0            0   
4           0               2             0                   1            1   

   Syncope  PVD / PAD  IHD  DCM  DM  HTN  SCD  RWMA(seen=1, not seen=0)  COPD  
0        0          0    0    0   0    0    0                         1     0  
1        0          0    0    0   1    1    0                         1     0  
2        0          0    0    0   1    0    0                         1     0  
3        0          0    0    0   0    0    0                         0     0  
4        0          0    0    0   0    0    0                         1     0

Now use the subset of features to fit models on training data

In [ ]:
best_features.shape,y.shape

((139, 0), (139,))